### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/spain54-g1-landing-page-with-react#1]
# Task List

- [x] Desde la rama develop, crear una nueva rama con el nombre de la feature
- [x] Crear el archivo del componente y desarrollar el componente.
- [x] Git add 'archivo del componente', luego git commit "feat: ..."
- [x] Realizar el push a origin de la rama de la feature.
- [x] En GitHub, create Pull Request with Reviewer a la rama develop sin realizar el merge.
- [x] Un compañero revisa, aprueba, y realiza el merge a develop
- [x] Borramos ramas de la feature (en GitHub y en el local)
- [x] En el local, realizamos un pull en develop (para actualizar nuestra rama local develop con lo que contiene el repo en GitHub)
